// @generated — DO NOT EDIT MANUALLY
// Generated by scripts/generate-icons.mjs from SVG source files

/**
 * @reverieio/icons-core
 *
 * Framework-agnostic SVG icon data.
 * This package contains pure data — no framework dependencies.
 */

// ── Types ───────────────────────────────────────────────────────────────────
export type {
  IconVariation,
  IconElement,
  IconLayer,
  IconDefinition,
  IconSet,
  IconMetadata,
  BaseIconProps,
} from './types'

// ── Builders (for creating custom icons) ────────────────────────────────────
export {
  path,
  circle,
  rect,
  line,
  polyline,
  polygon,
  ellipse,
  strokeLayer,
  fillLayer,
  defineIcon,
} from './define'

// ── Icon data ───────────────────────────────────────────────────────────────
export { default as beaker } from './icons/beaker'
export { default as bottle } from './icons/bottle'
export { default as droplet } from './icons/droplet'
export { default as flask } from './icons/flask'
export { default as pyramid } from './icons/pyramid'
export { default as sparkle } from './icons/sparkle'

// ── Registry (all icons in one map) ─────────────────────────────────────────
import type { IconSet } from './types'

import _beaker from './icons/beaker'
import _bottle from './icons/bottle'
import _droplet from './icons/droplet'
import _flask from './icons/flask'
import _pyramid from './icons/pyramid'
import _sparkle from './icons/sparkle'

/** Complete registry of all icons, keyed by name */
export const iconRegistry: Record<string, IconSet> = {
  beaker: _beaker,
  bottle: _bottle,
  droplet: _droplet,
  flask: _flask,
  pyramid: _pyramid,
  sparkle: _sparkle,
}

/** Get an icon set by name (returns undefined if not found) */
export function getIcon(name: string): IconSet | undefined {
  return iconRegistry[name]
}

/** Get a specific variation of an icon */
export function getIconVariation(name: string, variation: 'outline' | 'solid' | 'duotone' | 'bulk'): import('./types').IconDefinition | undefined {
  return iconRegistry[name]?.[variation]
}

// ── Metadata re-exports ─────────────────────────────────────────────────────
export { iconMetadata, searchIcons, getIconsByCategory, getIconNames, iconCategories } from './metadata'
export type { IconCategory } from './metadata'
