// @generated — DO NOT EDIT MANUALLY
// Generated by scripts/generate-icons.mjs from SVG source files

/**
 * @reverieio/icons-react
 *
 * React components for the Reverie icon library.
 * Each icon is available in 4 variations: Outline, Solid, Duotone, Bulk.
 *
 * @example
 *   import { FlaskOutline, DropletSolid } from '@reverieio/icons-react'
 *   <FlaskOutline size={24} color="#6A89A7" />
 *
 * Dynamic usage:
 *   import { Icon } from '@reverieio/icons-react'
 *   <Icon name="flask" variation="duotone" size={24} />
 */

import {
  beaker,
  bottle,
  droplet,
  flask,
  pyramid,
  sparkle,
} from '@reverieio/icons-core'

import { createReactIcon } from './createReactIcon'

// ── Re-exports ──────────────────────────────────────────────────────────────
export { createReactIcon, createReactIconSet } from './createReactIcon'
export type { ReverieIconProps } from './createReactIcon'
export { default as Icon } from './Icon'
export type { DynamicIconProps } from './Icon'

// Re-export core utilities for convenience
export { iconRegistry, getIcon, getIconVariation, searchIcons, iconMetadata, getIconNames } from '@reverieio/icons-core'
export type { IconVariation, IconSet, IconDefinition, IconMetadata } from '@reverieio/icons-core'

// ── Beaker ───────────────────────────────────────────────────────────────────
export const BeakerOutline          = createReactIcon('BeakerOutline', beaker.outline)
export const BeakerSolid            = createReactIcon('BeakerSolid', beaker.solid)
export const BeakerDuotone          = createReactIcon('BeakerDuotone', beaker.duotone)
export const BeakerBulk             = createReactIcon('BeakerBulk', beaker.bulk)

// ── Bottle ───────────────────────────────────────────────────────────────────
export const BottleOutline          = createReactIcon('BottleOutline', bottle.outline)
export const BottleSolid            = createReactIcon('BottleSolid', bottle.solid)
export const BottleDuotone          = createReactIcon('BottleDuotone', bottle.duotone)
export const BottleBulk             = createReactIcon('BottleBulk', bottle.bulk)

// ── Droplet ───────────────────────────────────────────────────────────────────
export const DropletOutline         = createReactIcon('DropletOutline', droplet.outline)
export const DropletSolid           = createReactIcon('DropletSolid', droplet.solid)
export const DropletDuotone         = createReactIcon('DropletDuotone', droplet.duotone)
export const DropletBulk            = createReactIcon('DropletBulk', droplet.bulk)

// ── Flask ───────────────────────────────────────────────────────────────────
export const FlaskOutline           = createReactIcon('FlaskOutline', flask.outline)
export const FlaskSolid             = createReactIcon('FlaskSolid', flask.solid)
export const FlaskDuotone           = createReactIcon('FlaskDuotone', flask.duotone)
export const FlaskBulk              = createReactIcon('FlaskBulk', flask.bulk)

// ── Pyramid ───────────────────────────────────────────────────────────────────
export const PyramidOutline         = createReactIcon('PyramidOutline', pyramid.outline)
export const PyramidSolid           = createReactIcon('PyramidSolid', pyramid.solid)
export const PyramidDuotone         = createReactIcon('PyramidDuotone', pyramid.duotone)
export const PyramidBulk            = createReactIcon('PyramidBulk', pyramid.bulk)

// ── Sparkle ───────────────────────────────────────────────────────────────────
export const SparkleOutline         = createReactIcon('SparkleOutline', sparkle.outline)
export const SparkleSolid           = createReactIcon('SparkleSolid', sparkle.solid)
export const SparkleDuotone         = createReactIcon('SparkleDuotone', sparkle.duotone)
export const SparkleBulk            = createReactIcon('SparkleBulk', sparkle.bulk)

